name: Run Tests and Generate Reports

on:
  pull_request:
    types: [closed]

jobs:
  run-tests-and-generate-reports:
    name: Run Tests and Generate Reports
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run tests and generate reports
      - name: Run tests and generate reports
        run: |
          set +e
          mvn clean test
          TEST_RESULT=$?
          mvn jacoco:report
          mvn allure:report
          exit $TEST_RESULT

        # Upload  Surefire reports
      - name: Upload Surefire Reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      # Save reports to a folder with branch name and timestamp
      - name: Save reports
        if: always()
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          REPORT_DIR="reports/${BRANCH_NAME}_${TIMESTAMP}"
          mkdir -p $REPORT_DIR
          cp -r target/site/jacoco $REPORT_DIR/jacoco || true
          cp -r target/site/allure-maven-plugin $REPORT_DIR/allure || true
          echo "Reports saved to $REPORT_DIR"

      # Upload reports as artifacts
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/

  publish-allure-report:
    name: Publish Allure Report
    needs: run-tests-and-generate-reports
    if: github.event.pull_request.merged == true && always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Copy Allure report to docs folder for GitHub Pages
        run: |
          rm -rf docs
          cp -r target/site/allure-maven-plugin docs

      - name: Commit and push Allure report to main/docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --cached --quiet || git commit -m "Update Allure report in docs"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}