name: Run tests and publish coverage report

on:
  pull_request:
    types: [closed]

jobs:
  test:
    name: Run Tests and Publish Allure Report
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: |
          set +e
          mvn clean test
          TEST_RESULT=$?
          mvn jacoco:report
          mvn allure:report
          exit $TEST_RESULT

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Save reports
        if: always()
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          REPORT_DIR="reports/${BRANCH_NAME}_${TIMESTAMP}"
          mkdir -p $REPORT_DIR
          cp -r target/site/jacoco $REPORT_DIR/jacoco || true
          cp -r reports/allure $REPORT_DIR/allure || true
          echo "Reports saved to $REPORT_DIR"

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/